# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'APLNetworkLayer/Utilities', :path => '../../'
  
  
  target 'SampleTests' do
     inherit! :search_paths
    # Pods for testing
    pod 'APLNetworkLayer/Utilities', :path => '../../'
   end

end
